### ISSUE TITLE
Text blurbs for editing

### ISSUE THREAD

**Issue by Fonta1n3** [BlockchainCommons/URVault-iOS#22]
Hey @shannona 

Please see the below text blurbs for potential editing:

* Intro

```
UR Vault is a specialist app designed to create a secure and redundant place for all your sensitive QR codes to be stored.

UR Vault utilizes multiple layers of encryption, 2FA (two factor authentication) along with your devices keychain to ensure only you may ever access your data.

UR Vault automatically creates fully encrypted iCloud backups and will sync to any other device where you are logged in with the same Apple ID.

All data stored on the iCloud is encrypted with a private key which is itself encrypted and stored on your device secure enclave. To ensure the app can sync across devices or easily be recovered on another device you must enable "keychain sync" under your iCloud settings on your devices.
```

* License & Disclaimer

```
Please read and accept the terms of our disclaimer:

            The use of UR Vault is under the "BSD 2-Clause Plus Patent License" (https://spdx.org/licenses/BSD-2-Clause-Patent.html). Copyright © 2019 BlockchainCommons. All rights reserved. With the disclaimer: THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
```

* Apple 2FA

```
UR Vault always encrypts your data before saving it.

UR Vault uses Apple's native 2FA (two factor authentication) to ensure only you can decrypt and access your QR codes.

Upon first use of the app we ask you to "Sign in with Apple" so that we can save your Apple ID username.

Everytime you launch the app you will be prompted to "Sign in with Apple" to ensure only you may access and decrypt your data.

If someone else tries to access the app all data will self destruct after 5 failed attempts!
```

* Camera prompt

```
UR Vault works best when you give it permission to scan QR codes you would like to save securely.

You may scan static or animated QR codes. UR Vault is designed to work especially well with Uniform Resource encoding but will work with any QR code.

Please tap "Grant Camera Permission" to allow UR Vault to access your camera so that it may scan QR codes.
```

**Comment by shannona** [comment]
@Fonta1n3, here are some edits. I only included text where I made changes.

* Intro

```
UR Vault creates a secure and redundant place to store all of your sensitive QR codes. Any QR code can be stored, but UR Vault is built especially to support Uniform Resources that are encoded as QRs, including seeds, HD keys, and account maps.

UR Vault utilizes multiple layers of encryption, 2FA (two factor authentication), and your device's keychain to ensure that only you may ever access your data.

UR Vault also creates secure resilience by automatically backing up your data to iCloud using backups that ​will sync to any other device where you are logged in with the same Apple ID. All data stored on the iCloud is fully encrypted with a private key that is itself encrypted and stored on your device's secure enclave. To ensure the app can sync across devices or easily be recovered on another device you must enable "keychain sync" under the iCloud settings on your devices.
```

* Apple 2FA

```
UR Vault always encrypts your data before saving it and uses Apple's native 2FA (two factor authentication) to ensure that only you can decrypt and access that information.

Upon your first use of UR Vault, you will need to "Sign in with Apple", then every time you launch the app you will again be prompted to "Sign in with Apple", to ensure that only you can access and decrypt your data. Your Apple ID information is only used by the app, not shared with Blockchain Commons!

If someone else tries to access the app, all data will self destruct after 5 failed attempts!
```

* Camera prompt

```
UR Vault works best when you give it permission to scan QR codes that you would like to save securely.

You may scan static or animated QR codes. UR Vault is designed to work especially well with Uniform Resource encoding, but will work with any QR code.

Please tap "Grant Camera Permission" to allow UR Vault to access your camera so that it can scan QR codes.
```

**Comment by shannona** [comment]
@Fonta1n3,

I can't change the Apple DESCRIPTION any more because the app has now been accepted for review, so here's how I think it should read:
==
STORE YOUR SEEDS, PRIVATE KEYS, AND SSKR SHARES!

UR Vault is a secure place to store sensitive QR codes with automated and encrypted iCloud backups. Any QR code can be stored, but UR Vault is built especially to support Uniform Resources that are encoded as QRs. These Uniform Resources (URs) are a new encoding format intended to help developers store security sensitive data and communicate it between applications and platforms. Specifically designed with Bitcoin usage in mind, many UR "types" are Bitcoin related.

UR Vault is thus a great place to store extended keys, SSKR shards, transactions, or even seeds. Not only can it be used to store all of your secrets, but you can share information with family members and ask them to store items for you, which is ideally suited for backing up and assisting in recovering lost Bitcoin keys.

Features:
- Bitcoin Focus
You can store your seeds or extended keys. Ask friends and family to store your SSKR shards for account recovery.

- Two-Factor Protection
Apple's 2FA (two factor authentication) can be used to ensure that only you can ever access your data and decrypt it.

- Encrypted Backups for All Your Devices
UR Vault utilizes its own encryption key to store your data fully encrypted in the iCloud. This ensures that if you lose your device, you can recover all your data with a new device as long as you are logged in with the same Apple ID. (In order for this to function you must enable "keychain sync" in your devices iCloud settings.)

- Private Data
Your data is never shared with any third parties; only your device and your iCloud account can access and decrypt your QR codes.

- Animated QRs
UR Vault takes advantage of animated QR codes to allow users to easily store and recover data that is too large to fit into a single QR. This is ideal for "partially signed bitcoin transactions" (PSBTs), which can be too large for a single QR.

- UR Data Types
UR Vault converts known types into UR and back again. If the item you are saving is an unknown type *and* too large to save in a single QR code you will be able to export it as "ur:bytes", which other UR compatible apps also support.

- PSBT Conversion
You may also add PSBTs in base64 format and automatically convert them to animated "ur:crypto-psbt" QR codes.

To read more about the app check out the repo at: https://github.com/BlockchainCommons/URVault-iOS

To read more about Uniform Resource check out the repo at: https://github.com/BlockchainCommons/Research

To read more about Blockchain Commons visit our website: https://www.blockchaincommons.com

**Comment by shannona** [comment]
Since we're in between release submissions at the moment, I was able to update the Apple description to the above.

@Fonta1n3 has said the edited text is in the release, so I'm closing this.
